### PR TITLE
Reworked front-end workflow

### PR DESCRIPTION
**Pull request by michieldewilde**
Structure app can be changed (assets). Can't find a universal browsersync for vagrant and a normal another method of hosting.

### CODE REVIEW

**Comment by nicoverbruggen** [comment]
:+1: 

Much appreciated, Michiel! I'll see this gets merged in, but in `develop` instead.`master` is reserved for releases ;)

(So if possible, work on `develop`, that makes things easier.)

**Comment by michieldewilde** [comment]
I committed on develop but I wasn't thinking when I merged.

**Comment by nicoverbruggen** [comment]
Since the styling was done in the bower_components _variables file of bootstrap-sass, some of the markup has reverted to Bootstrap's original. Since I was planning to redo the style, this doesn't matter much. Everything else seems to work as required.

**Comment by nicoverbruggen** [comment]
Merged!

**Pull request closed without merging**
